# Generated by Django 4.0.6 on 2022-09-26 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sac', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='phone',
            field=models.CharField(max_length=255),
        ),
    ]
