# Generated by Django 4.0.6 on 2022-09-26 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sac', '0002_alter_alert_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='attachment',
            field=models.FileField(null=True, upload_to='public'),
        ),
    ]
