# Generated by Django 4.0.6 on 2022-09-26 15:54

from django.db import migrations, models
import private_storage.fields
import private_storage.storage.files


class Migration(migrations.Migration):

    dependencies = [
        ('sac', '0003_alert_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='private_file',
            field=private_storage.fields.PrivateFileField(null=True, storage=private_storage.storage.files.PrivateFileSystemStorage(), upload_to='private'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
